services:
  postgres:
    image: postgres:latest
    container_name: HootPostgreSQL
    ports:
      - "6500:5432"
    volumes:
      - postgres-data:/data
    env_file:
      - ./.env

  pgAdmin:
    image: dpage/pgadmin4
    container_name: HootPgAdmin
    env_file:
      - ./.env
    ports:
      - "5050:80"
    volumes:
      - pg-admin:/data

networks:
  app-network:
    driver: host

volumes:
  pg-admin:
  postgres-data:
